AllCops:
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10
